### ISSUE TITLE
Include mypyc compiled wheels in the distribution

### ISSUE THREAD

**Issue by DetachHead** [KotlinIsland/basedmypy#104]
We can retroactively release the wheels I think.

### Original issue
basedmypy is slow

![image](https://user-images.githubusercontent.com/57028336/146315039-aa1ac7b1-127e-4111-b3af-9fde74c9f189.png)
![image](https://user-images.githubusercontent.com/57028336/146315053-b46efba4-50d8-42fa-964f-f0de76b67406.png)

**Comment by KotlinIsland** [comment]
This should be resolved in 1.3
