### ISSUE TITLE
wrong commit hash on mypy version for dev installs 

### ISSUE THREAD

**Issue by DetachHead** [KotlinIsland/basedmypy#112]
```
>mypy -V
basedmypy 2.0.0+dev.41706dcab733a05a6f43d4739832508cda54c4ad
mypy 0.940+dev.41706dcab733a05a6f43d4739832508cda54c4ad
```
it uses the basedmypy commit on both

**Comment by KotlinIsland** [comment]
I think manually hardcoding it each time bm is rebased onto upstream would be a great way to handle this.

**Comment by DetachHead** [comment]
sounds sus, is there a command or something that can be run to find the latest commit from the upstream

**Comment by KotlinIsland** [comment]
Nothing that I know of. I don't think it seems sus, it will just be part of the sync process.

**Comment by KotlinIsland** [comment]
Actually, do we even need to include the mypy commit hash? is it that useful for local development.

I think I'll just remove that part, but manually include it in the release version

**Comment by DetachHead** [comment]
i think if release versions of basedmypy are based on an unreleased version of mypy it should include the hash, otherwise it makes it difficult to narrow down issues like #110

**Comment by KotlinIsland** [comment]
currently released versions do have the hash, and I'm planning pinned releases as well. For local dev I think just not including the mypy version is fine.

**Comment by Zeckie** [comment]
The current message implies that it is using mypy, rather than being a fork of mypy. It definitely seems odd when it reports a different mypy version to the one I have installed.

```
C:\>pip list | findstr mypy
basedmypy                         1.1.3
mypy                              0.910
mypy-extensions                   0.4.3

C:\>mypy --version
basedmypy 1.1.3
mypy 0.920 (4d2ff58e)

C:\>pip uninstall basedmypy
Found existing installation: basedmypy 1.1.3
Uninstalling basedmypy-1.1.3:
...
  Successfully uninstalled basedmypy-1.1.3

C:\>mypy --version
mypy 0.910

C:\>pip list | findstr mypy
mypy                              0.910
mypy-extensions                   0.4.3

C:\>

```
