### ISSUE TITLE
baselined error messages with line numbers in them re-appear when the line number changes

### ISSUE THREAD

**Issue by DetachHead** [KotlinIsland/basedmypy#113]
![image](https://user-images.githubusercontent.com/57028336/146874545-9959d2a6-bb8e-4180-a4db-ec051b686493.png)

**Comment by KotlinIsland** [comment]
This shouldn't be too hard to fix, just filter out "line \d+" when comparing the message.

**Comment by KotlinIsland** [comment]
theres probs other dynamic messages like this
