### ISSUE TITLE
`assert_type` function

### ISSUE THREAD

**Issue by DetachHead** [KotlinIsland/basedmypy#122]
maybe only exists at type time similar to `reveal_type`?
```py
def assert_type(value: T, t: type[T]) -> T:
    assert isinstance(value, t)
```
doesnt work because
```py
assert_type(1, str)
```
just gets widened to `object`

**Comment by DetachHead** [comment]
```py
class assert_type(Generic[T]):
    def __new__(cls: Self, value: T) -> None:  # type:ignore[misc]
        pass
```
![image](https://user-images.githubusercontent.com/57028336/147321439-aa778560-5fff-4111-a246-bf31332ea95b.png)

**Comment by KotlinIsland** [comment]
Can you add a usage, type time and run time if possible

**Comment by DetachHead** [comment]
added in https://github.com/KotlinIsland/basedtyping/pull/7

**Comment by KotlinIsland** [comment]
related #249
