### ISSUE TITLE
Rename `NoReturn` to `Never`

### ISSUE THREAD

**Issue by DetachHead** [KotlinIsland/basedmypy#135]

**Comment by KotlinIsland** [comment]
Do you mean in error messages? or is this more of a `basedtyping` issue?

**Comment by DetachHead** [comment]
i was thinking more like in the vendored typeshed, but ig it has to be done in both basedtyping and basedtypeshed

**Comment by DetachHead** [comment]
![image](https://user-images.githubusercontent.com/57028336/148307376-84c2640b-60c3-41ce-a574-547764ae51da.png)
wait how do we rename this

**Comment by KotlinIsland** [comment]
It's part of `typing` so it's more relevant to `basedtyping` than `basedmypy`.

**Comment by KotlinIsland** [comment]
KotlinIsland/basedtyping/issues/20
