### ISSUE TITLE
A safe write baseline mode that doesn't add errors, just updates existing ones and subtracts non existent ones

### ISSUE THREAD

**Issue by KotlinIsland** [KotlinIsland/basedmypy#161]
Often you don't want to accidentally add to the baseline, so a mode that only removes and updates the line number/message of existing errors would be good.

If it is safe enough it could be on by default.

**Comment by DetachHead** [comment]
i think running mypy without any flags automatically write to the baseline with this mode as long as it hasn't found any new errors
