### ISSUE TITLE
Unionize the duck types

### ISSUE THREAD

**Issue by KotlinIsland** [KotlinIsland/basedmypy#168]
An option to unionize the duck types.

```py
a: float
reveal_type(a)  # float | int
```

I think a configuration option like `duck_types` with values of `unionize`, `plain`(#167) and `standard`

relates: #6
relates: #167

**Comment by Zeckie** [comment]
> unionize
 (verb): become or cause to become members of a trade union.

Are ducks eligible to join trade unions? And what does this have to do with mypy?

#252

**Comment by KotlinIsland** [comment]
#167 wins
