### ISSUE TITLE
Store offset within class / function in the baseline

### ISSUE THREAD

**Issue by Zeckie** [KotlinIsland/basedmypy#183]
Locations of errors stored in baseline file are currently using filename and line number within that file.

Sometimes, making a change such as adding a new function to a file moves the other lines within the file far enough that they are not recognised (If I remember correctly, they can move up to 50 lines and still be recognised). 

Would it be possible to also record the class / function(s), and an offset relative to the function `def`? That way, if a one function is added / modified, the baselined errors in a different function will still reliably be recognised.

**Comment by KotlinIsland** [comment]
Related #134

**Comment by KotlinIsland** [comment]
Groundwork for this this is implemented in #212

**Comment by KotlinIsland** [comment]
Merged this with #134

Duplicate of #134
