### ISSUE TITLE
`reveal_type` can be ignored when incorrectly matched from the baseline

### ISSUE THREAD

**Issue by Zeckie** [KotlinIsland/basedmypy#191]
### Describe the problem, ie expected/actual result (if it's not blatantly obvious)

I added  `reveal_type(some_variable)` in my code, and ran basedmypy on the file.

### Gist to reproduce
```py
a: Any
print(a)
```
`mypy --write-baseline .`
```py
a: Any
reveal_type(a)
print(a)
```

### Basedmypy version

basedmypy 1.2.2
Based on mypy 0.940+dev (fa16759d)

**Comment by KotlinIsland** [comment]
caused by #159
