### ISSUE TITLE
Define / clarify what based is

### ISSUE THREAD

**Issue by Zeckie** [KotlinIsland/basedmypy#200]
Using the word **based** without specifying what is it based on makes no sense.

Are some usages trying to refer to the ability to store a baseline of current errors, and hide errors in that baseline during subsequent runs?

https://github.com/KotlinIsland/basedmypy
> **Based** static typing for Python 3 and 2 that makes breaking changes from PEP 484. **Based**? **Based** on what?

https://github.com/KotlinIsland/basedmypy#what-is-basedmypy
> Basedmypy is a fork of mypy that adds **based** functionality and ...

https://github.com/KotlinIsland/basedmypy/issues/114
> Would be very **based** as you ...

Were those translated from another language?

**Comment by ethan-xd** [comment]
> based? based on what?

**Comment by Zeckie** [comment]
> > based? based on what?

Yes, that is an important question that needs an answer.

**Comment by DetachHead** [comment]
Did You Know? full form of BASED:

B - Breaking
A - Ancient
S - Standards
E - Everyone
D - Despises

**Comment by ethan-xd** [comment]
why did you close this? we never figured out what it was based on!

**Comment by DetachHead** [comment]
@ethan-xd 
![image](https://user-images.githubusercontent.com/57028336/157035343-a64cfbdc-c702-4b6a-b4d8-ce82b9567cda.png)

**Comment by Zeckie** [comment]
I guess we just have to open a new issue

**Comment by Zeckie** [comment]
Pretty much every usage of the word `based` should be replaced with either `forked` or `baselined`.

**Comment by shitpostbotmin** [comment]
> Pretty much every usage of the word `based` should be replaced with either `forked` or `baselined`.


![processed](https://user-images.githubusercontent.com/56467888/157154802-de63a286-b8d5-4b2c-98e4-6d11897b9131.jpeg)
