### ISSUE TITLE
Misuse of the word `based`

### ISSUE THREAD

**Issue by Zeckie** [KotlinIsland/basedmypy#252]
Issue [200](https://github.com/KotlinIsland/basedmypy/issues/200) was closed without the issue being addressed. The [backronym](https://github.com/KotlinIsland/basedmypy/issues/200#issuecomment-1050477719) was clearly a joke.

> Using the word **based** without specifying what is it based on makes no sense.
> 
> Are some usages trying to refer to the ability to store a baseline of current errors, and hide errors in that baseline during subsequent runs?
> 
> https://github.com/KotlinIsland/basedmypy
> > **Based** static typing for Python 3 and 2 that makes breaking changes from PEP 484. **Based**? **Based** on what?
> 
> https://github.com/KotlinIsland/basedmypy#what-is-basedmypy
> > Basedmypy is a fork of mypy that adds **based** functionality and ...
> 
> https://github.com/KotlinIsland/basedmypy/issues/114
> > Would be very **based** as you ...
> 
> Were those translated from another language?
>

**Comment by Zeckie** [comment]
There is a typo in the label `basedline`

**Comment by DetachHead** [comment]
it's actually industry standard to use funny backronyms when naming your projects. see [git](https://en.wikipedia.org/wiki/Git#Naming)

> "git" can mean anything, depending on your mood.
> 
> - Random three-letter combination that is pronounceable, and not actually used by any common UNIX command. The fact that it is a mispronunciation of "get" may or may not be relevant.
> - Stupid. Contemptible and despicable. Simple. Take your pick from the dictionary of slang.
> - "Global information tracker": you're in a good mood, and it actually works for you. Angels sing, and a light suddenly fills the room.
> - "Goddamn idiotic truckload of sh*t": when it breaks.

*- @torvalds (author of the smash hit linux)*

**Comment by Zeckie** [comment]
> Closing as this is a joke issue

This is a serious issue, i've renamed it to make it a bit clearer

**Comment by Zeckie** [comment]
> it's actually industry standard to use funny backronyms when naming your projects. see [git](https://en.wikipedia.org/wiki/Git#Naming)

But does git start misusing g as a an adjective throughout their documentation?
