### ISSUE TITLE
Ability to type an attribute as `Untyped`

### ISSUE THREAD

**Issue by KotlinIsland** [KotlinIsland/basedmypy#267]
To help with usability of `Any` and to make working with generated stubs easier, an `Untyped` annotation would provide a great deal of utility.
```py
# some_stub.pyi
a: Untyped
```
```py
# some_mod.py
import some_stub

print(some_stub.a)  # error: using untyped member in typed context
```

**Comment by Zeckie** [comment]
Isn't this the default behaviour when there is no type annotation?

**Comment by KotlinIsland** [comment]
> Isn't that already the default behaviour when there is no type annotation?

Similar, but an `Untyped` annotation would be a more specialized form of `Any` that could fill a prominent gap in the use case or gradually typing vendored stubs:

current:
```py
print(some_stub.a)  # error: expression contains Any
some_stub.a = 1)  # no error
a: int = some_stub.a  # no error
```

All of these cases will produce contextual errors if the attribute is typed with `Untyped`.
