### ISSUE TITLE
Detect code in stubs

### ISSUE THREAD

**Issue by Zeckie** [KotlinIsland/basedmypy#275]
Pick up where someone has copied a `.py` file and changed it to `.pyi` to become a stub.

The following make no sense in stubs:
- a function with a body (the body will never be run, but basedmypy currently checks them)
- code, such as function calls, loops etc

**Comment by KotlinIsland** [comment]
This is something that [flake8-pyi](https://github.com/PyCQA/flake8-pyi) already covers, I see no reason to reinvent this.
