### ISSUE TITLE
Re-add strict mode and add a `non-strict` option

### ISSUE THREAD

**Issue by KotlinIsland** [KotlinIsland/basedmypy#282]
The use case is that `legacy` sounds like it means it disables all based features (there's probably a use case for that). But a `non-strict` flag that sets strictness to `legacy` level but doesn't disable any based stuff would be good.

**Comment by KotlinIsland** [comment]
Any prediction on this? 🔮

**Comment by DetachHead** [comment]
why not just keep the name `strict` from upstream instead of creating a seperate `non-strict` mode? then just make `strict` enabled by default

**Comment by KotlinIsland** [comment]
yeah
