### ISSUE TITLE
Store the line of src an error is on in the baseline

### ISSUE THREAD

**Issue by KotlinIsland** [KotlinIsland/basedmypy#302]
Storing the source code snippet is a really solid way to improve matching, especially on static error messages like `no-any-expr`.

**Comment by DetachHead** [comment]
isn't that what it used to do?

**Comment by KotlinIsland** [comment]
Not the line number, the actual source code on that line.

**Comment by Zeckie** [comment]
Would it be possible / a good idea to store the whole statement, in cases of multi-line statements?

**Comment by KotlinIsland** [comment]
I think it would be best to store the AST of the statement, as then you could even avoid formatting alterations.

**Comment by Zeckie** [comment]
Is mypy's ast stable across different mypy / python versions?

**Comment by Zeckie** [comment]
Could it store the source code, but compare by converting both to AST?
