### ISSUE TITLE
infer from overloads, add default value of impl

### ISSUE THREAD

**Issue by KotlinIsland** [KotlinIsland/basedmypy#325]
```py
def foo(a: int, b: int): ...
def foo(a: str): ...
def foo(a, b=None):
    reveal_type(b)  # int | None
```

Would it be good if the default value from the impl was added to the type?

Good suggestion from @DetachHead, it should only work when one of the overloads doesn't have that parameter.

**Comment by DetachHead** [comment]
i think this should only be allowed when there's an overload that doesn't include that parameter, otherwise it seems like a more confusing version of the already deprecated `implicit_optional`

```py
@overload
def foo(a: int, b: int): ...
@overload
def foo(a: str): ...
def foo(a, b = None):
    reveal_type(b)  # int | None
```
