### ISSUE TITLE
Should `Never`/`<nothing>`/`NoReturn`/`UninhabitedType`/`bottom type`/`zero type`/`empty type`/`⊥` render with extra info?

### ISSUE THREAD

**Issue by KotlinIsland** [KotlinIsland/basedmypy#372]
```py
reveal_type([])  # Never (from nothing)
a: Never
reveal_type(a)  # Never
```

**Comment by DetachHead** [comment]
i don't think so. the existence of `NoReturn`, `<nothing>` and `Never` is already confusing enough. imo it shopuld just always render as `Never` no matter what. rendering `NoReturn` as `Never` imo will help people understand that `NoReturn` means `Never`

ig if you wanted to show more info like whether or not it's inferred, you could change `<nothing>` to `Never (inferred)` but i don't see the point in doing that when no other type is rendered with info like that

**Comment by KotlinIsland** [comment]
`Any` is

**Comment by DetachHead** [comment]
because `Any` is a sus type that can be caused by many different things. imo `Never` isn't as dangerous so that info isn't as useful

**Comment by KotlinIsland** [comment]
I do see the intention of naming it `Nothing` like Kotlin/Scala, where it's like "What's the type of `[]`?, oh it's `List<Nothing>`, because there's nothing in the list"

```py
a = []
reveal_type(a)  # list[Never]
reveal_type(a)  # list[Nothing]
```
I think in this case the second is much more understandable if you don't have a solid grasp of the uninhabited type.

**Comment by KotlinIsland** [comment]
Hmmmm, good point
