### ISSUE TITLE
Invent a way to type this

### ISSUE THREAD

**Issue by KotlinIsland** [KotlinIsland/basedmypy#377]
```py
def foo(iterable):
    assert all(isinstance(it, int) for it in iterable)
    return list(iterable)
```

It might seem like the solution would be something like:
```py
def foo[T: int](iterable: Iterable[T]) -> list[T]: ..
```
But that doesn't hold true for 
```py
i: list[int] | list[bool]
```
Because what is `T` going to be specified as? `int | bool` is just `int` therefore the function returns `list[int]`.

Just look at:
```py
a: list[int] | list[bool]
b = list(a)
reveal_type(b) # list[int]
```
Sus

Consider:
```py
a: int | str
reveal_type([a])  # list[int | str]
```
This looks 'correct' to me, while it would be true to say that `[a]` could be either a `list[int]` or `list[bool]`, but that sounds more annoying than anything.

Maybe the solution is #365?, such that
```py
def f[T: int](i: Iterable[T]) -> list[T]: ...

i: list[int] | list[bool]
f(i)  # def f(i: Iterable[int] | Iterable[bool]) -> list[int] | list[bool]: ...
```

**Comment by Zeckie** [comment]
When passing in a union to a function call, would it make sense for basedmypy to consider each combination separately?

So for `foo(i)` it would determine the result type for `i: list[int]` and `i: list[bool]` and then combine the types as a union at the end (`list[int] | list[bool]`)?

Maybe that would only be required where the parameter type affects the return type (through a TypeVar or overload)

**Comment by KotlinIsland** [comment]
> When passing in a union to a function call, would it make sense for basedmypy to consider each combination separately?

That's what #365 is about

**Comment by KotlinIsland** [comment]
Next time if you have a vague idea or suggestion, please take it to [discussions](https://github.com/KotlinIsland/basedmypy/discussions) general
