### ISSUE TITLE
option to hide notes from errors that refer to other lines

### ISSUE THREAD

**Issue by DetachHead** [KotlinIsland/basedmypy#387]
```py
def foo(): ...  # "foo" defined here
foo(a=1)
```
it's confusing when they are displayed in IDEs

**Comment by KotlinIsland** [comment]
@DetachHead Can we have an egg

**Comment by DetachHead** [comment]
Eggs are for chickens

**Comment by KotlinIsland** [comment]
```py
def foo(): ...
foo(a=1)
```

**Comment by KotlinIsland** [comment]
- Related: #468

**Comment by DetachHead** [comment]
looks like `--hide-error-context` is supposed to do this, but i think theres cases where it still shows the context. i cant find any examples tho

**Comment by KotlinIsland** [comment]
`--show-error-context` has nothing to do with this:
![image](https://github.com/KotlinIsland/basedmypy/assets/65446343/c015b294-8c6f-4b06-80f2-0968aee7660a)

https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-show-error-context
