### ISSUE TITLE
Use the term "higher kinded types" instead of "Nested TypeVars"

### ISSUE THREAD

**Issue by NeilGirdhar** [KotlinIsland/basedmypy#447]
The readme says: "With nested TypeVars you are able to have functions with polymorphic generic parameters."  I believe these are called higher kinded types: https://github.com/python/typing/issues/548

**Comment by KotlinIsland** [comment]
hahaha, I was thinking that the wording looked wrong. Hmmm, I don't think they are they same thing. 'nested typevars' allow you to write

```py
X = TypeVar("X")
Y = TypeVar("Y", bound=list[X])
```

Whereas hkt are like:
```py
X = TypeVar('X')
Y = TypeVar('Y', type_vars=X)
```

Or am I wrong?

**Comment by NeilGirdhar** [comment]
I'm not sure to be honest.   However, I don't know what `Y = TypeVar('Y', type_vars=X)` means.

**Comment by KotlinIsland** [comment]
I don't really understand hkt, but I think they mean like, a `TypeVar` that has it's own `TypeVar`s.

**Comment by NeilGirdhar** [comment]
I guess you're right that your nested types don't do everything that HKT is supposed to?  If we write things using the new [PEP 695](https://peps.python.org/pep-0695/) notation it might be clearer:

Your function:
```
def f[X: Any, Y: list[X]](x: X, y: Y): ...
```
General HKT:
```
def f[X: Any, Y: Any](x: X[Y]): ...
```

**Comment by KotlinIsland** [comment]
@NeilGirdhar
- I raised it #450
