### ISSUE TITLE
`BASEDMYPY_TYPE_CHECKING` variable

### ISSUE THREAD

**Issue by DetachHead** [KotlinIsland/basedmypy#524]
it would be nice to have a variable like `TYPE_CHECKING` that's only true in basedmypy, so we can conditionally support based features while still supporting regular type checkers:

```py
from basedtyping import BASEDMYPY_TYPE_CHECKING

if IS_BASEDMYPY:
    foo: Foo & Bar
else:
    foo: object
```

related: #37

**Comment by KotlinIsland** [comment]
Something like this?
```py
BASEDMYPY: Literal[False] = False

If BASEDMYPY:
    A = B & C
else:
    A = object
```
```
> mypy --always-true BASEDMYPY
```

**Comment by DetachHead** [comment]
Yeah but it should be enabled by default

**Comment by KotlinIsland** [comment]
There is `MYPY`, can we close this issue?

**Comment by DetachHead** [comment]
nah, because not only does it not work at all, it also won't allow for conditionally defining stuff depending on whether you're using basedmypy or mypy, like in my example

**Comment by KotlinIsland** [comment]
What about we introduce `BASEDMYPY`, equivalent to `MYPY`?
