### ISSUE TITLE
support configuration with a separate "basedmypy" section in pyproject.toml

### ISSUE THREAD

**Issue by DetachHead** [KotlinIsland/basedmypy#607]
vscode complains about basedmypy options because they're not in the json schema hosted oon schemastore: https://json.schemastore.org/partial-mypy.json

![image](https://github.com/KotlinIsland/basedmypy/assets/57028336/a25ace88-9bc0-474a-bfd2-c0f68edfb31f)

i suggest using a separate "basedmypy" section with its own schema file

**Comment by KotlinIsland** [comment]
- duplicate-of #158

Maybe we could merge these two issues
