### ISSUE TITLE
ignore missing type annotation for `_` parameter

### ISSUE THREAD

**Issue by 00001H** [KotlinIsland/basedmypy#677]
e.g.
```py
def foo(x: int,_) -> int:#Error, but I don't want it to be
    ...
```

Sometimes, when you want to pass a function as a callback, it would be nice not to have to annotate the 9 ignored parameter.

**Comment by KotlinIsland** [comment]
This should cover your case?
```py
def foo(x: int, *args: object, **kwargs: object) -> int:
    ...
```

**Comment by KotlinIsland** [comment]
Actually, I think I like your idea

**Comment by KotlinIsland** [comment]
> Sometimes, when you want to pass a function as a callback, it would be nice not to have to annotate the 9 ignored parameter.

When you have more than 1 unused parameter, how are you naming them? you can't have multiple parameters with the same name. `_`, `__`?

**Comment by 00001H** [comment]
*_ would do.
