### ISSUE TITLE
format baseline json

### ISSUE THREAD

**Issue by DetachHead** [KotlinIsland/basedmypy#94]
currently its all in 1 line which is annoying

# Workaround

Format the baseline manually before committing (but if the baseline file is too big most IDEs will refuse to let you format it)

**Comment by Zeckie** [comment]
Having it being a single line makes tracking changes difficult (eg. in GitLab MRs, it shows as `Changes are too large to be shown.`)

**Comment by Zeckie** [comment]
Would also be useful for it to work with git blame
