### ISSUE TITLE
different error levels (eg. warning & error)

### ISSUE THREAD

**Issue by DetachHead** [KotlinIsland/basedmypy#96]
eg. if i'm using basedmypy in an ide and i want baselined errors to appear as warnings and new errors to appear as errors

**Comment by DetachHead** [comment]
maybe baselined errors can appear as note, which already exists

**Comment by DetachHead** [comment]
#111 covers this, having a seperate "warning" level seems pointless imo, error and note are the only ones we need

**Comment by KotlinIsland** [comment]
Closing this for now as it seems to be a dupe of #111, mypy can report warnings, but it currently only does in the daemon.

And I'm not sure what benefit warnings would have, to stick around and stink up the output? why not just raise errors.

If someone has a good use case for warnings I'd be happy to listen 😀
